# Generated by Django 5.2.15 on 2026-07-03 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('github_id', models.CharField(db_index=True, max_length=100)),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('sync_branch', models.CharField(default='main', max_length=100)),
                ('visibility', models.CharField(default='public', max_length=50)),
                ('primary_language', models.CharField(blank=True, default='', max_length=100)),
                ('installation_id', models.CharField(blank=True, default='', max_length=100)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('processing_status', models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=50)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='workspaces.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='authentication.workspace')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
            },
        ),
    ]
