# Generated by Django 5.2.15 on 2026-07-04 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('rationale', models.TextField(blank=True)),
                ('module_name', models.CharField(blank=True, default='', max_length=255)),
                ('adr_source', models.CharField(blank=True, default='', max_length=255)),
                ('developer_name', models.CharField(blank=True, default='', max_length=255)),
                ('commit_hash', models.CharField(blank=True, default='', max_length=100)),
                ('pr_number', models.CharField(blank=True, default='', max_length=100)),
                ('incident_key', models.CharField(blank=True, default='', max_length=100)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='repositories.repository')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='repositories.architecturedecision')),
            ],
            options={
                'verbose_name': 'Architecture Decision',
                'verbose_name_plural': 'Architecture Decisions',
                'db_table': 'architecture_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionAlternative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternative_text', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='repositories.architecturedecision')),
            ],
            options={
                'verbose_name': 'Decision Alternative',
                'verbose_name_plural': 'Decision Alternatives',
                'db_table': 'decision_alternatives',
            },
        ),
        migrations.CreateModel(
            name='DecisionConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constraint_text', models.TextField()),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='repositories.architecturedecision')),
            ],
            options={
                'verbose_name': 'Decision Constraint',
                'verbose_name_plural': 'Decision Constraints',
                'db_table': 'decision_constraints',
            },
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='repositories.architecturedecision')),
            ],
            options={
                'verbose_name': 'Decision History',
                'verbose_name_plural': 'Decision Histories',
                'db_table': 'decision_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_key', models.CharField(max_length=100)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='repositories.architecturedecision')),
            ],
            options={
                'verbose_name': 'Decision Incident',
                'verbose_name_plural': 'Decision Incidents',
                'db_table': 'decision_incidents',
            },
        ),
    ]
